import { lazy } from 'react';
import type { DemoMeta, SectionMeta, SectionId } from '@/types/demo';

export const SECTIONS: SectionMeta[] = [
  { id: 'fundamentals', title: 'Fundamentals', icon: '🧱' },
  { id: 'media', title: 'Media & Streams', icon: '📷' },
  { id: 'datachannels', title: 'Data Channels', icon: '📡' },
  { id: 'audiovideo', title: 'Audio & Video', icon: '🎥' },
  { id: 'advanced', title: 'Advanced', icon: '🔬' },
  { id: 'multiparty', title: 'Multi-Party', icon: '👥' },
  { id: 'cuttingedge', title: 'Cutting Edge', icon: '🚀' },
  { id: 'games', title: 'Fun & Games', icon: '🎮' },
];

export const DEMOS: DemoMeta[] = [
  // Section 1 — Fundamentals
  {
    id: 'hello-webrtc',
    title: 'Hello WebRTC',
    path: '/demos/hello-webrtc',
    section: 'fundamentals',
    difficulty: 'beginner',
    description: 'Your first RTCPeerConnection — connect two peers on the same page via loopback.',
    tags: ['RTCPeerConnection', 'loopback', 'offer', 'answer'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section1-fundamentals/HelloWebRTC')),
  },
  {
    id: 'connection-states',
    title: 'Connection States',
    path: '/demos/connection-states',
    section: 'fundamentals',
    difficulty: 'beginner',
    description: 'Watch the RTCPeerConnection state machine animate through every state transition.',
    tags: ['connectionState', 'iceConnectionState', 'state machine'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section1-fundamentals/ConnectionStates')),
  },
  {
    id: 'sdp-inspector',
    title: 'SDP Inspector',
    path: '/demos/sdp-inspector',
    section: 'fundamentals',
    difficulty: 'beginner',
    description: 'Paste any SDP and explore its structure — codecs, ICE candidates, extensions.',
    tags: ['SDP', 'offer', 'answer', 'codec', 'ice'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section1-fundamentals/SdpInspector')),
  },
  {
    id: 'ice-candidate-explorer',
    title: 'ICE Candidate Explorer',
    path: '/demos/ice-candidate-explorer',
    section: 'fundamentals',
    difficulty: 'beginner',
    description: 'See every ICE candidate as it arrives — host, server reflexive, and relay types.',
    tags: ['ICE', 'candidate', 'STUN', 'TURN', 'trickle'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section1-fundamentals/IceCandidateExplorer')),
  },
  {
    id: 'manual-signaling',
    title: 'Manual Signaling',
    path: '/demos/manual-signaling',
    section: 'fundamentals',
    difficulty: 'beginner',
    description: 'Copy-paste offer and answer SDP between two browser tabs — no server needed.',
    tags: ['signaling', 'offer', 'answer', 'copy-paste'],
    needsServer: false,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section1-fundamentals/ManualSignaling')),
  },

  // Section 2 — Media & Streams
  {
    id: 'camera-mic-preview',
    title: 'Camera & Mic Preview',
    path: '/demos/camera-mic-preview',
    section: 'media',
    difficulty: 'beginner',
    description: 'Request camera and microphone access and preview the stream locally.',
    tags: ['getUserMedia', 'MediaStream', 'camera', 'microphone'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section2-media/CameraMicPreview')),
  },
  {
    id: 'device-picker',
    title: 'Device Picker',
    path: '/demos/device-picker',
    section: 'media',
    difficulty: 'beginner',
    description: 'Enumerate all cameras and microphones and switch between them.',
    tags: ['enumerateDevices', 'MediaDeviceInfo', 'camera', 'microphone'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section2-media/DevicePicker')),
  },
  {
    id: 'screen-share',
    title: 'Screen Share',
    path: '/demos/screen-share',
    section: 'media',
    difficulty: 'beginner',
    description: 'Share your screen or a window and view it through a loopback WebRTC connection.',
    tags: ['getDisplayMedia', 'screen share', 'loopback'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section2-media/ScreenShare')),
  },
  {
    id: 'media-constraints-lab',
    title: 'Media Constraints Lab',
    path: '/demos/media-constraints-lab',
    section: 'media',
    difficulty: 'intermediate',
    description: 'Experiment with resolution, frame rate, and codec constraints in real time.',
    tags: ['MediaTrackConstraints', 'applyConstraints', 'resolution', 'framerate'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section2-media/MediaConstraintsLab')),
  },

  // Section 3 — Data Channels
  {
    id: 'p2p-chat',
    title: 'P2P Chat',
    path: '/demos/p2p-chat',
    section: 'datachannels',
    difficulty: 'intermediate',
    description: 'Send text messages directly between two browser tabs via an RTCDataChannel.',
    tags: ['RTCDataChannel', 'chat', 'p2p', 'text'],
    needsServer: false,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section3-datachannels/P2PChat')),
  },
  {
    id: 'data-channel-types',
    title: 'Data Channel Types',
    path: '/demos/data-channel-types',
    section: 'datachannels',
    difficulty: 'intermediate',
    description: 'Compare ordered vs unordered, reliable vs unreliable data channel modes.',
    tags: ['RTCDataChannel', 'ordered', 'reliable', 'maxRetransmits'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/DataChannelTypes')),
  },
  {
    id: 'file-transfer',
    title: 'File Transfer',
    path: '/demos/file-transfer',
    section: 'datachannels',
    difficulty: 'intermediate',
    description: 'Transfer files between tabs with backpressure control and SHA-256 verification.',
    tags: ['RTCDataChannel', 'file', 'ArrayBuffer', 'backpressure', 'SHA-256'],
    needsServer: false,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section3-datachannels/FileTransfer')),
  },
  {
    id: 'json-state-sync',
    title: 'JSON State Sync',
    path: '/demos/json-state-sync',
    section: 'datachannels',
    difficulty: 'intermediate',
    description: 'Keep a JSON object synchronized between two peers in real time.',
    tags: ['RTCDataChannel', 'JSON', 'sync', 'state'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/JsonStateSync')),
  },
  {
    id: 'emoji-reactions',
    title: 'Emoji Reaction Burst',
    path: '/demos/emoji-reactions',
    section: 'datachannels',
    difficulty: 'beginner',
    description: 'Send emoji reactions over a WebRTC DataChannel and watch them float up the screen in real time.',
    tags: ['RTCDataChannel', 'JSON', 'animation', 'reactions'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/EmojiReactions')),
  },
  {
    id: 'p2p-clipboard',
    title: 'P2P Clipboard',
    path: '/demos/p2p-clipboard',
    section: 'datachannels',
    difficulty: 'beginner',
    description: 'Instantly share text and images between browser tabs via RTCDataChannel — no server needed.',
    tags: ['RTCDataChannel', 'Clipboard API', 'text', 'image', 'sync'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/P2PClipboard')),
  },
  {
    id: 'morse-code-radio',
    title: 'Morse Code Radio',
    path: '/demos/morse-code-radio',
    section: 'datachannels',
    difficulty: 'beginner',
    description: 'Type a message to hear it in Morse code via Web Audio — and transmit it over a DataChannel.',
    tags: ['RTCDataChannel', 'Web Audio', 'OscillatorNode', 'Morse code'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/MorseCodeRadio')),
  },
  {
    id: 'latency-ping',
    title: 'Latency Ping Monitor',
    path: '/demos/latency-ping',
    section: 'datachannels',
    difficulty: 'intermediate',
    description: 'Measure RTCDataChannel round-trip time with a continuous ping/pong loop — graphed live.',
    tags: ['RTCDataChannel', 'RTT', 'latency', 'ping', 'recharts'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/LatencyPing')),
  },

  // Section 4 — Audio & Video
  {
    id: 'video-call',
    title: 'Video Call',
    path: '/demos/video-call',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Full A/V video call between two tabs with automatic WebSocket signaling.',
    tags: ['video', 'audio', 'WebSocket', 'signaling', 'getUserMedia'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section4-audiovideo/VideoCall')),
  },
  {
    id: 'audio-visualizer',
    title: 'Audio Visualizer',
    path: '/demos/audio-visualizer',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Visualize audio waveforms and frequency spectra through a WebRTC loopback.',
    tags: ['Web Audio API', 'AnalyserNode', 'waveform', 'spectrum'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/AudioVisualizer')),
  },
  {
    id: 'video-effects',
    title: 'Video Effects',
    path: '/demos/video-effects',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Apply grayscale, blur, and edge detection to video via Canvas pipeline.',
    tags: ['canvas', 'captureStream', 'video effects', 'CanvasRenderingContext2D'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/VideoEffects')),
  },
  {
    id: 'bandwidth-quality',
    title: 'Bandwidth & Quality',
    path: '/demos/bandwidth-quality',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Control bitrate constraints and see quality impact in a loopback call.',
    tags: ['RTCRtpSender', 'setParameters', 'bitrate', 'bandwidth'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/BandwidthQuality')),
  },
  {
    id: 'ascii-webcam',
    title: 'ASCII Webcam Art',
    path: '/demos/ascii-webcam',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Convert your live webcam feed into real-time ASCII art using the Canvas 2D API.',
    tags: ['getUserMedia', 'canvas', 'ASCII', 'pixel data', 'ImageData'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/AsciiWebcam')),
  },
  {
    id: 'motion-detector',
    title: 'Motion Detector',
    path: '/demos/motion-detector',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Detect movement in your webcam feed by comparing frames with canvas pixel differencing.',
    tags: ['getUserMedia', 'canvas', 'frame differencing', 'motion', 'ImageData'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/MotionDetector')),
  },
  {
    id: 'live-captions',
    title: 'Live Captions',
    path: '/demos/live-captions',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Auto-transcribe speech with the Web Speech API and broadcast captions to peers via DataChannel.',
    tags: ['SpeechRecognition', 'Web Speech API', 'RTCDataChannel', 'captions', 'accessibility'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section4-audiovideo/LiveCaptions')),
  },
  {
    id: 'voice-changer',
    title: 'Voice Changer',
    path: '/demos/voice-changer',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Apply echo, telephone, tremolo, distortion, and robot effects to your mic via Web Audio nodes.',
    tags: ['Web Audio API', 'DelayNode', 'WaveShaper', 'BiquadFilter', 'getUserMedia'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/VoiceChanger')),
  },
  {
    id: 'speech-emoji',
    title: 'Speech to Emoji',
    path: '/demos/speech-emoji',
    section: 'audiovideo',
    difficulty: 'beginner',
    description: 'Speak and watch your words transform into emoji — translated and broadcast to peers via DataChannel.',
    tags: ['SpeechRecognition', 'Web Speech API', 'emoji', 'RTCDataChannel', 'fun'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/SpeechEmoji')),
  },

  // Section 5 — Advanced
  {
    id: 'stats-dashboard',
    title: 'Stats Dashboard',
    path: '/demos/stats-dashboard',
    section: 'advanced',
    difficulty: 'intermediate',
    description: 'Live RTCStatsReport charts — bitrate, packet loss, jitter, RTT over time.',
    tags: ['RTCStatsReport', 'getStats', 'bitrate', 'packet loss', 'charts'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section5-advanced/StatsDashboard')),
  },
  {
    id: 'stun-turn-tester',
    title: 'STUN/TURN Tester',
    path: '/demos/stun-turn-tester',
    section: 'advanced',
    difficulty: 'intermediate',
    description: 'Test custom STUN/TURN servers and verify candidate types gathered.',
    tags: ['STUN', 'TURN', 'ICE', 'RTCIceServer', 'candidate'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section5-advanced/StunTurnTester')),
  },
  {
    id: 'screen-annotation',
    title: 'Screen Share + Annotation',
    path: '/demos/screen-annotation',
    section: 'advanced',
    difficulty: 'advanced',
    description: 'Share your screen and annotate it collaboratively via WebSocket signaling.',
    tags: ['getDisplayMedia', 'canvas', 'annotation', 'collaboration'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section5-advanced/ScreenAnnotation')),
  },
  {
    id: 'encrypted-messenger',
    title: 'Encrypted Messenger',
    path: '/demos/encrypted-messenger',
    section: 'advanced',
    difficulty: 'advanced',
    description: 'End-to-end encrypted chat using ECDH key exchange and AES-256-GCM via the Web Crypto API.',
    tags: ['Web Crypto API', 'ECDH', 'AES-GCM', 'encryption', 'key exchange'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section5-advanced/EncryptedMessenger')),
  },
  {
    id: 'datachannel-speedtest',
    title: 'DataChannel Speed Test',
    path: '/demos/datachannel-speedtest',
    section: 'advanced',
    difficulty: 'intermediate',
    description: 'Saturate an RTCDataChannel with binary data and measure peak throughput in real time.',
    tags: ['RTCDataChannel', 'ArrayBuffer', 'backpressure', 'throughput', 'bandwidth'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section5-advanced/SpeedTest')),
  },

  // Section 6 — Multi-Party
  {
    id: 'mesh-network',
    title: 'Mesh Network',
    path: '/demos/mesh-network',
    section: 'multiparty',
    difficulty: 'advanced',
    description: 'Connect 3-4 peers in a full mesh — every peer connects to every other peer.',
    tags: ['mesh', 'multi-party', 'RTCPeerConnection', 'signaling'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section6-multiparty/MeshNetwork')),
  },
  {
    id: 'broadcaster-viewer',
    title: 'Broadcaster / Viewer',
    path: '/demos/broadcaster-viewer',
    section: 'multiparty',
    difficulty: 'advanced',
    description: 'One broadcaster sends to multiple viewers — SFU-style topology without an SFU.',
    tags: ['broadcast', 'viewer', 'one-to-many', 'signaling'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section6-multiparty/BroadcasterViewer')),
  },
  {
    id: 'group-chat',
    title: 'Group Chat',
    path: '/demos/group-chat',
    section: 'multiparty',
    difficulty: 'advanced',
    description: 'Multi-peer text chat over RTCDataChannels — no server relay for messages.',
    tags: ['RTCDataChannel', 'group', 'mesh', 'chat'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section6-multiparty/GroupChat')),
  },

  // Section 7 — Cutting Edge
  {
    id: '3d-video',
    title: '3D Video with Three.js',
    path: '/demos/3d-video',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Stream video onto a 3D spinning cube texture via Three.js and WebRTC loopback.',
    tags: ['Three.js', 'WebGL', 'VideoTexture', '3D', 'loopback'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/ThreeDVideo')),
  },
  {
    id: 'virtual-background',
    title: 'Virtual Background (ML)',
    path: '/demos/virtual-background',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Replace or blur your background using TensorFlow.js body segmentation.',
    tags: ['TensorFlow.js', 'body segmentation', 'virtual background', 'ML', 'canvas'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/VirtualBackground')),
  },
  {
    id: 'collaborative-whiteboard',
    title: 'Collaborative Whiteboard',
    path: '/demos/collaborative-whiteboard',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Draw together on a shared canvas — strokes sync via RTCDataChannel.',
    tags: ['canvas', 'RTCDataChannel', 'collaboration', 'drawing'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section7-cuttingedge/CollaborativeWhiteboard')),
  },
  {
    id: 'webAudio-synth',
    title: 'WebAudio Synth Jam',
    path: '/demos/webAudio-synth',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Play synthesizer notes together — audio generated via Tone.js, streamed over WebRTC.',
    tags: ['Tone.js', 'Web Audio', 'synthesizer', 'RTCDataChannel', 'jam'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section7-cuttingedge/WebAudioSynth')),
  },
  {
    id: 'color-palette',
    title: 'Live Color Palette',
    path: '/demos/color-palette',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'Extract the dominant color palette from your live webcam feed using real-time color quantization.',
    tags: ['getUserMedia', 'canvas', 'color quantization', 'ImageData', 'palette'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/ColorPalette')),
  },
  {
    id: 'beat-machine',
    title: 'Collaborative Beat Machine',
    path: '/demos/beat-machine',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Build beats together — a 16-step drum sequencer powered by Tone.js, synced over RTCDataChannel.',
    tags: ['Tone.js', 'Web Audio', 'sequencer', 'RTCDataChannel', 'drum machine'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section7-cuttingedge/BeatMachine')),
  },
  {
    id: 'fractal-explorer',
    title: 'Fractal Explorer',
    path: '/demos/fractal-explorer',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'Explore the Mandelbrot set with smooth coloring — pan, zoom, and sync your viewport over DataChannel.',
    tags: ['canvas', 'ImageData', 'Mandelbrot', 'fractal', 'DataChannel', 'sync'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/FractalExplorer')),
  },
  {
    id: 'gravity-sim',
    title: 'Particle Gravity Sim',
    path: '/demos/gravity-sim',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'Click to place gravity wells and watch particles orbit — well positions sync over RTCDataChannel.',
    tags: ['canvas', 'N-body simulation', 'physics', 'DataChannel', 'particles'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/GravitySim')),
  },
  {
    id: 'webrtc-theremin',
    title: 'WebRTC Theremin',
    path: '/demos/webrtc-theremin',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'Play a virtual theremin with your mouse — pitch and volume control via Tone.js, streamed over WebRTC.',
    tags: ['Tone.js', 'Oscillator', 'MediaStreamDestination', 'theremin', 'Web Audio'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/WebRTCTheremin')),
  },
  {
    id: 'matrix-rain',
    title: 'Matrix Digital Rain',
    path: '/demos/matrix-rain',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'The iconic Matrix rain on canvas — captured via captureStream() and streamed over WebRTC.',
    tags: ['canvas', 'captureStream', 'MediaStream', 'animation', 'loopback'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/MatrixRain')),
  },
  {
    id: 'kaleidoscope-webcam',
    title: 'Kaleidoscope Webcam',
    path: '/demos/kaleidoscope-webcam',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'Transform your live webcam into a mesmerizing kaleidoscope using Canvas 2D clip and rotate.',
    tags: ['getUserMedia', 'canvas', 'captureStream', 'transform', 'clip'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/KaleidoscopeWebcam')),
  },

  // Section 8 — Fun & Games
  {
    id: 'multiplayer-pong',
    title: 'Multiplayer Pong',
    path: '/demos/multiplayer-pong',
    section: 'games',
    difficulty: 'intermediate',
    description: 'Classic Pong with paddle positions synced via RTCDataChannel — two players, one page.',
    tags: ['RTCDataChannel', 'canvas', 'game', 'keyboard', 'loopback'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/MultiplayerPong')),
  },
  {
    id: 'etch-a-sketch',
    title: 'Cooperative Etch-a-Sketch',
    path: '/demos/etch-a-sketch',
    section: 'games',
    difficulty: 'beginner',
    description: 'Draw on a shared canvas where one peer controls X and the other controls Y via RTCDataChannel.',
    tags: ['RTCDataChannel', 'canvas', 'cooperative', 'drawing', 'keyboard'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/EtchASketch')),
  },
  {
    id: 'confetti-party',
    title: 'Confetti Party',
    path: '/demos/confetti-party',
    section: 'games',
    difficulty: 'beginner',
    description: 'Trigger canvas-confetti explosions that sync to all peers in the room via RTCDataChannel.',
    tags: ['RTCDataChannel', 'canvas-confetti', 'animation', 'fun', 'multi-tab'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section8-games/ConfettiParty')),
  },
  {
    id: 'pixel-art-collab',
    title: 'Collaborative Pixel Art',
    path: '/demos/pixel-art-collab',
    section: 'games',
    difficulty: 'beginner',
    description: 'Paint on a shared 32×32 canvas — every stroke syncs to your peer via RTCDataChannel.',
    tags: ['RTCDataChannel', 'canvas', 'pixel art', 'collaboration', 'drawing'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/PixelArtCollab')),
  },
  {
    id: 'snake-race',
    title: 'Snake Race',
    path: '/demos/snake-race',
    section: 'games',
    difficulty: 'intermediate',
    description: 'Two snakes compete for the same food — new food positions sync over RTCDataChannel.',
    tags: ['RTCDataChannel', 'canvas', 'game', 'snake', 'competitive'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/SnakeRace')),
  },
  {
    id: 'dice-roll-room',
    title: 'Dice Roll Room',
    path: '/demos/dice-roll-room',
    section: 'games',
    difficulty: 'beginner',
    description: 'Roll dice together — every roll is broadcast to all peers in the room via RTCDataChannel.',
    tags: ['RTCDataChannel', 'SVG', 'dice', 'tabletop', 'signaling'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section8-games/DiceRollRoom')),
  },
  {
    id: 'shared-cursors',
    title: 'Shared Cursors',
    path: '/demos/shared-cursors',
    section: 'games',
    difficulty: 'beginner',
    description: 'See everyone\'s mouse cursor in real time — throttled position broadcast over RTCDataChannel.',
    tags: ['RTCDataChannel', 'mousemove', 'cursor', 'collaboration', 'awareness'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section8-games/SharedCursors')),
  },
  {
    id: 'wordle-duel',
    title: 'Wordle Duel',
    path: '/demos/wordle-duel',
    section: 'games',
    difficulty: 'beginner',
    description: 'Race to solve the daily Wordle — same word derived from the date, solve-status synced over DataChannel.',
    tags: ['RTCDataChannel', 'word game', 'Wordle', 'daily', 'competitive'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/WordleDuel')),
  },
  {
    id: 'qr-teleporter',
    title: 'QR Code Teleporter',
    path: '/demos/qr-teleporter',
    section: 'games',
    difficulty: 'intermediate',
    description: 'Encode a message as a QR code, stream it over WebRTC video, and decode it on the other end with jsQR.',
    tags: ['canvas', 'captureStream', 'qrcode', 'jsQR', 'video stream'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/QrTeleporter')),
  },
];

export function getDemosBySection(sectionId: SectionId): DemoMeta[] {
  return DEMOS.filter((d) => d.section === sectionId);
}

export function getDemoById(id: string): DemoMeta | undefined {
  return DEMOS.find((d) => d.id === id);
}
