import { lazy } from 'react';
import type { DemoMeta, SectionMeta, SectionId } from '@/types/demo';

export const SECTIONS: SectionMeta[] = [
  { id: 'fundamentals', title: 'Fundamentals', icon: '🧱' },
  { id: 'media', title: 'Media & Streams', icon: '📷' },
  { id: 'datachannels', title: 'Data Channels', icon: '📡' },
  { id: 'audiovideo', title: 'Audio & Video', icon: '🎥' },
  { id: 'advanced', title: 'Advanced', icon: '🔬' },
  { id: 'multiparty', title: 'Multi-Party', icon: '👥' },
  { id: 'cuttingedge', title: 'Cutting Edge', icon: '🚀' },
  { id: 'games', title: 'Fun & Games', icon: '🎮' },
  { id: 'mashups', title: 'Mashups', icon: '🧪' },
];

export const DEMOS: DemoMeta[] = [
  // Section 1 — Fundamentals
  {
    id: 'hello-webrtc',
    title: 'Hello WebRTC',
    path: '/demos/hello-webrtc',
    section: 'fundamentals',
    difficulty: 'beginner',
    description: 'Your first RTCPeerConnection — connect two peers on the same page via loopback.',
    tags: ['RTCPeerConnection', 'loopback', 'offer', 'answer'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section1-fundamentals/HelloWebRTC')),
  },
  {
    id: 'connection-states',
    title: 'Connection States',
    path: '/demos/connection-states',
    section: 'fundamentals',
    difficulty: 'beginner',
    description: 'Watch the RTCPeerConnection state machine animate through every state transition.',
    tags: ['connectionState', 'iceConnectionState', 'state machine'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section1-fundamentals/ConnectionStates')),
  },
  {
    id: 'sdp-inspector',
    title: 'SDP Inspector',
    path: '/demos/sdp-inspector',
    section: 'fundamentals',
    difficulty: 'beginner',
    description: 'Paste any SDP and explore its structure — codecs, ICE candidates, extensions.',
    tags: ['SDP', 'offer', 'answer', 'codec', 'ice'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section1-fundamentals/SdpInspector')),
  },
  {
    id: 'ice-candidate-explorer',
    title: 'ICE Candidate Explorer',
    path: '/demos/ice-candidate-explorer',
    section: 'fundamentals',
    difficulty: 'beginner',
    description: 'See every ICE candidate as it arrives — host, server reflexive, and relay types.',
    tags: ['ICE', 'candidate', 'STUN', 'TURN', 'trickle'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section1-fundamentals/IceCandidateExplorer')),
  },
  {
    id: 'manual-signaling',
    title: 'Manual Signaling',
    path: '/demos/manual-signaling',
    section: 'fundamentals',
    difficulty: 'beginner',
    description: 'Copy-paste offer and answer SDP between two browser tabs — no server needed.',
    tags: ['signaling', 'offer', 'answer', 'copy-paste'],
    needsServer: false,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section1-fundamentals/ManualSignaling')),
  },

  // Section 2 — Media & Streams
  {
    id: 'camera-mic-preview',
    title: 'Camera & Mic Preview',
    path: '/demos/camera-mic-preview',
    section: 'media',
    difficulty: 'beginner',
    description: 'Request camera and microphone access and preview the stream locally.',
    tags: ['getUserMedia', 'MediaStream', 'camera', 'microphone'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section2-media/CameraMicPreview')),
  },
  {
    id: 'device-picker',
    title: 'Device Picker',
    path: '/demos/device-picker',
    section: 'media',
    difficulty: 'beginner',
    description: 'Enumerate all cameras and microphones and switch between them.',
    tags: ['enumerateDevices', 'MediaDeviceInfo', 'camera', 'microphone'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section2-media/DevicePicker')),
  },
  {
    id: 'screen-share',
    title: 'Screen Share',
    path: '/demos/screen-share',
    section: 'media',
    difficulty: 'beginner',
    description: 'Share your screen or a window and view it through a loopback WebRTC connection.',
    tags: ['getDisplayMedia', 'screen share', 'loopback'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section2-media/ScreenShare')),
  },
  {
    id: 'media-constraints-lab',
    title: 'Media Constraints Lab',
    path: '/demos/media-constraints-lab',
    section: 'media',
    difficulty: 'intermediate',
    description: 'Experiment with resolution, frame rate, and codec constraints in real time.',
    tags: ['MediaTrackConstraints', 'applyConstraints', 'resolution', 'framerate'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section2-media/MediaConstraintsLab')),
  },

  // Section 3 — Data Channels
  {
    id: 'p2p-chat',
    title: 'P2P Chat',
    path: '/demos/p2p-chat',
    section: 'datachannels',
    difficulty: 'intermediate',
    description: 'Send text messages directly between two browser tabs via an RTCDataChannel.',
    tags: ['RTCDataChannel', 'chat', 'p2p', 'text'],
    needsServer: false,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section3-datachannels/P2PChat')),
  },
  {
    id: 'data-channel-types',
    title: 'Data Channel Types',
    path: '/demos/data-channel-types',
    section: 'datachannels',
    difficulty: 'intermediate',
    description: 'Compare ordered vs unordered, reliable vs unreliable data channel modes.',
    tags: ['RTCDataChannel', 'ordered', 'reliable', 'maxRetransmits'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/DataChannelTypes')),
  },
  {
    id: 'file-transfer',
    title: 'File Transfer',
    path: '/demos/file-transfer',
    section: 'datachannels',
    difficulty: 'intermediate',
    description: 'Transfer files between tabs with backpressure control and SHA-256 verification.',
    tags: ['RTCDataChannel', 'file', 'ArrayBuffer', 'backpressure', 'SHA-256'],
    needsServer: false,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section3-datachannels/FileTransfer')),
  },
  {
    id: 'json-state-sync',
    title: 'JSON State Sync',
    path: '/demos/json-state-sync',
    section: 'datachannels',
    difficulty: 'intermediate',
    description: 'Keep a JSON object synchronized between two peers in real time.',
    tags: ['RTCDataChannel', 'JSON', 'sync', 'state'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/JsonStateSync')),
  },
  {
    id: 'crdt-sticky-notes',
    title: 'CRDT Sticky Notes',
    path: '/demos/crdt-sticky-notes',
    section: 'datachannels',
    difficulty: 'advanced',
    description: 'Peer-to-peer sticky-note board powered by Yjs CRDT updates over RTCDataChannel.',
    tags: ['RTCDataChannel', 'Yjs', 'CRDT', 'collaboration', 'binary updates'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/CrdtStickyNotes')),
  },
  {
    id: 'markdown-newsroom',
    title: 'Markdown Newsroom',
    path: '/demos/markdown-newsroom',
    section: 'datachannels',
    difficulty: 'intermediate',
    description: 'Collaborative markdown broadcast desk with safe rendering and peer-synced scripts.',
    tags: ['RTCDataChannel', 'markdown-it', 'DOMPurify', 'editor', 'preview'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/MarkdownNewsroom')),
  },
  {
    id: 'patch-relay',
    title: 'Patch Relay',
    path: '/demos/patch-relay',
    section: 'datachannels',
    difficulty: 'advanced',
    description: 'Ship document deltas instead of full text by generating and applying patches over RTCDataChannel.',
    tags: ['RTCDataChannel', 'diff-match-patch', 'delta sync', 'editor', 'patch'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/PatchRelay')),
  },
  {
    id: 'emoji-reactions',
    title: 'Emoji Reaction Burst',
    path: '/demos/emoji-reactions',
    section: 'datachannels',
    difficulty: 'beginner',
    description: 'Send emoji reactions over a WebRTC DataChannel and watch them float up the screen in real time.',
    tags: ['RTCDataChannel', 'JSON', 'animation', 'reactions'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/EmojiReactions')),
  },
  {
    id: 'p2p-clipboard',
    title: 'P2P Clipboard',
    path: '/demos/p2p-clipboard',
    section: 'datachannels',
    difficulty: 'beginner',
    description: 'Instantly share text and images between browser tabs via RTCDataChannel — no server needed.',
    tags: ['RTCDataChannel', 'Clipboard API', 'text', 'image', 'sync'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/P2PClipboard')),
  },
  {
    id: 'morse-code-radio',
    title: 'Morse Code Radio',
    path: '/demos/morse-code-radio',
    section: 'datachannels',
    difficulty: 'beginner',
    description: 'Type a message to hear it in Morse code via Web Audio — and transmit it over a DataChannel.',
    tags: ['RTCDataChannel', 'Web Audio', 'OscillatorNode', 'Morse code'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/MorseCodeRadio')),
  },
  {
    id: 'binary-clock',
    title: 'Binary Clock Sync',
    path: '/demos/binary-clock',
    section: 'datachannels',
    difficulty: 'beginner',
    description: 'A BCD binary clock that measures clock skew between peers via RTCDataChannel ping/pong timing.',
    tags: ['RTCDataChannel', 'binary clock', 'BCD', 'clock skew', 'NTP'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/BinaryClock')),
  },
  {
    id: 'css-theme-sync',
    title: 'CSS Theme Sync',
    path: '/demos/css-theme-sync',
    section: 'datachannels',
    difficulty: 'beginner',
    description: 'Drag sliders to change hue, radius, blur, and scale — all CSS custom properties sync to peers via DataChannel.',
    tags: ['RTCDataChannel', 'CSS custom properties', 'theme', 'design', 'sync'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/CssThemeSync')),
  },
  {
    id: 'latency-ping',
    title: 'Latency Ping Monitor',
    path: '/demos/latency-ping',
    section: 'datachannels',
    difficulty: 'intermediate',
    description: 'Measure RTCDataChannel round-trip time with a continuous ping/pong loop — graphed live.',
    tags: ['RTCDataChannel', 'RTT', 'latency', 'ping', 'recharts'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/LatencyPing')),
  },

  // Section 4 — Audio & Video
  {
    id: 'video-call',
    title: 'Video Call',
    path: '/demos/video-call',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Full A/V video call between two tabs with automatic WebSocket signaling.',
    tags: ['video', 'audio', 'WebSocket', 'signaling', 'getUserMedia'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section4-audiovideo/VideoCall')),
  },
  {
    id: 'audio-visualizer',
    title: 'Audio Visualizer',
    path: '/demos/audio-visualizer',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Visualize audio waveforms and frequency spectra through a WebRTC loopback.',
    tags: ['Web Audio API', 'AnalyserNode', 'waveform', 'spectrum'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/AudioVisualizer')),
  },
  {
    id: 'video-effects',
    title: 'Video Effects',
    path: '/demos/video-effects',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Apply grayscale, blur, and edge detection to video via Canvas pipeline.',
    tags: ['canvas', 'captureStream', 'video effects', 'CanvasRenderingContext2D'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/VideoEffects')),
  },
  {
    id: 'bandwidth-quality',
    title: 'Bandwidth & Quality',
    path: '/demos/bandwidth-quality',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Control bitrate constraints and see quality impact in a loopback call.',
    tags: ['RTCRtpSender', 'setParameters', 'bitrate', 'bandwidth'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/BandwidthQuality')),
  },
  {
    id: 'ascii-webcam',
    title: 'ASCII Webcam Art',
    path: '/demos/ascii-webcam',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Convert your live webcam feed into real-time ASCII art using the Canvas 2D API.',
    tags: ['getUserMedia', 'canvas', 'ASCII', 'pixel data', 'ImageData'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/AsciiWebcam')),
  },
  {
    id: 'motion-detector',
    title: 'Motion Detector',
    path: '/demos/motion-detector',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Detect movement in your webcam feed by comparing frames with canvas pixel differencing.',
    tags: ['getUserMedia', 'canvas', 'frame differencing', 'motion', 'ImageData'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/MotionDetector')),
  },
  {
    id: 'live-captions',
    title: 'Live Captions',
    path: '/demos/live-captions',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Auto-transcribe speech with the Web Speech API and broadcast captions to peers via DataChannel.',
    tags: ['SpeechRecognition', 'Web Speech API', 'RTCDataChannel', 'captions', 'accessibility'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section4-audiovideo/LiveCaptions')),
  },
  {
    id: 'voice-changer',
    title: 'Voice Changer',
    path: '/demos/voice-changer',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Apply echo, telephone, tremolo, distortion, and robot effects to your mic via Web Audio nodes.',
    tags: ['Web Audio API', 'DelayNode', 'WaveShaper', 'BiquadFilter', 'getUserMedia'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/VoiceChanger')),
  },
  {
    id: 'speech-emoji',
    title: 'Speech to Emoji',
    path: '/demos/speech-emoji',
    section: 'audiovideo',
    difficulty: 'beginner',
    description: 'Speak and watch your words transform into emoji — translated and broadcast to peers via DataChannel.',
    tags: ['SpeechRecognition', 'Web Speech API', 'emoji', 'RTCDataChannel', 'fun'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/SpeechEmoji')),
  },
  {
    id: 'spectrogram',
    title: 'Audio Spectrogram',
    path: '/demos/spectrogram',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'A real-time waterfall spectrogram of your microphone — frequency on Y, time scrolling left, amplitude as heat color.',
    tags: ['AnalyserNode', 'FFT', 'spectrogram', 'frequency', 'waterfall'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/Spectrogram')),
  },
  {
    id: 'audio-feature-mirror',
    title: 'Audio Feature Mirror',
    path: '/demos/audio-feature-mirror',
    section: 'audiovideo',
    difficulty: 'advanced',
    description: 'Generate synthetic audio, send it through WebRTC, and analyze the remote stream with Meyda.',
    tags: ['Web Audio API', 'Meyda', 'Analyser', 'audio features', 'loopback'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/AudioFeatureMirror')),
  },

  // Section 5 — Advanced
  {
    id: 'stats-dashboard',
    title: 'Stats Dashboard',
    path: '/demos/stats-dashboard',
    section: 'advanced',
    difficulty: 'intermediate',
    description: 'Live RTCStatsReport charts — bitrate, packet loss, jitter, RTT over time.',
    tags: ['RTCStatsReport', 'getStats', 'bitrate', 'packet loss', 'charts'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section5-advanced/StatsDashboard')),
  },
  {
    id: 'stun-turn-tester',
    title: 'STUN/TURN Tester',
    path: '/demos/stun-turn-tester',
    section: 'advanced',
    difficulty: 'intermediate',
    description: 'Test custom STUN/TURN servers and verify candidate types gathered.',
    tags: ['STUN', 'TURN', 'ICE', 'RTCIceServer', 'candidate'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section5-advanced/StunTurnTester')),
  },
  {
    id: 'screen-annotation',
    title: 'Screen Share + Annotation',
    path: '/demos/screen-annotation',
    section: 'advanced',
    difficulty: 'advanced',
    description: 'Share your screen and annotate it collaboratively via WebSocket signaling.',
    tags: ['getDisplayMedia', 'canvas', 'annotation', 'collaboration'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section5-advanced/ScreenAnnotation')),
  },
  {
    id: 'encrypted-messenger',
    title: 'Encrypted Messenger',
    path: '/demos/encrypted-messenger',
    section: 'advanced',
    difficulty: 'advanced',
    description: 'End-to-end encrypted chat using ECDH key exchange and AES-256-GCM via the Web Crypto API.',
    tags: ['Web Crypto API', 'ECDH', 'AES-GCM', 'encryption', 'key exchange'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section5-advanced/EncryptedMessenger')),
  },
  {
    id: 'network-graph',
    title: 'Live Network Graph',
    path: '/demos/network-graph',
    section: 'advanced',
    difficulty: 'intermediate',
    description: 'Watch your WebRTC peer topology emerge as a live graph with animated data packets flying between nodes.',
    tags: ['canvas', 'topology', 'multi-peer', 'graph', 'visualization'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section5-advanced/NetworkGraph')),
  },
  {
    id: 'time-capsule',
    title: 'P2P Time Capsule',
    path: '/demos/time-capsule',
    section: 'advanced',
    difficulty: 'advanced',
    description: 'Write a secret message, seal it with timed AES-256-GCM — it only decrypts when the countdown expires.',
    tags: ['Web Crypto API', 'PBKDF2', 'AES-GCM', 'time-lock', 'DataChannel'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section5-advanced/TimeCapsule')),
  },
  {
    id: 'datachannel-speedtest',
    title: 'DataChannel Speed Test',
    path: '/demos/datachannel-speedtest',
    section: 'advanced',
    difficulty: 'intermediate',
    description: 'Saturate an RTCDataChannel with binary data and measure peak throughput in real time.',
    tags: ['RTCDataChannel', 'ArrayBuffer', 'backpressure', 'throughput', 'bandwidth'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section5-advanced/SpeedTest')),
  },
  {
    id: 'mermaid-signal-lab',
    title: 'Mermaid Signal Lab',
    path: '/demos/mermaid-signal-lab',
    section: 'advanced',
    difficulty: 'advanced',
    description: 'Co-edit Mermaid protocol diagrams and mirror them instantly between peers via RTCDataChannel.',
    tags: ['RTCDataChannel', 'Mermaid', 'sequence diagram', 'protocol', 'visualization'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section5-advanced/MermaidSignalLab')),
  },
  {
    id: 'compression-lab',
    title: 'Compression Lab',
    path: '/demos/compression-lab',
    section: 'advanced',
    difficulty: 'advanced',
    description: 'Compress peer payloads with fflate before they cross the data channel and inspect the savings.',
    tags: ['RTCDataChannel', 'fflate', 'compression', 'binary', 'bandwidth'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section5-advanced/CompressionLab')),
  },
  {
    id: 'csv-telemetry-studio',
    title: 'CSV Telemetry Studio',
    path: '/demos/csv-telemetry-studio',
    section: 'advanced',
    difficulty: 'advanced',
    description: 'Parse telemetry CSV with PapaParse and beam the dataset peer-to-peer for instant diagnostics.',
    tags: ['RTCDataChannel', 'PapaParse', 'CSV', 'telemetry', 'dashboard'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section5-advanced/CsvTelemetryStudio')),
  },

  // Section 6 — Multi-Party
  {
    id: 'mesh-network',
    title: 'Mesh Network',
    path: '/demos/mesh-network',
    section: 'multiparty',
    difficulty: 'advanced',
    description: 'Connect 3-4 peers in a full mesh — every peer connects to every other peer.',
    tags: ['mesh', 'multi-party', 'RTCPeerConnection', 'signaling'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section6-multiparty/MeshNetwork')),
  },
  {
    id: 'broadcaster-viewer',
    title: 'Broadcaster / Viewer',
    path: '/demos/broadcaster-viewer',
    section: 'multiparty',
    difficulty: 'advanced',
    description: 'One broadcaster sends to multiple viewers — SFU-style topology without an SFU.',
    tags: ['broadcast', 'viewer', 'one-to-many', 'signaling'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section6-multiparty/BroadcasterViewer')),
  },
  {
    id: 'group-chat',
    title: 'Group Chat',
    path: '/demos/group-chat',
    section: 'multiparty',
    difficulty: 'advanced',
    description: 'Multi-peer text chat over RTCDataChannels — no server relay for messages.',
    tags: ['RTCDataChannel', 'group', 'mesh', 'chat'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section6-multiparty/GroupChat')),
  },

  // Section 7 — Cutting Edge
  {
    id: '3d-video',
    title: '3D Video with Three.js',
    path: '/demos/3d-video',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Stream video onto a 3D spinning cube texture via Three.js and WebRTC loopback.',
    tags: ['Three.js', 'WebGL', 'VideoTexture', '3D', 'loopback'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/ThreeDVideo')),
  },
  {
    id: 'virtual-background',
    title: 'Virtual Background (ML)',
    path: '/demos/virtual-background',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Replace or blur your background using TensorFlow.js body segmentation.',
    tags: ['TensorFlow.js', 'body segmentation', 'virtual background', 'ML', 'canvas'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/VirtualBackground')),
  },
  {
    id: 'collaborative-whiteboard',
    title: 'Collaborative Whiteboard',
    path: '/demos/collaborative-whiteboard',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Draw together on a shared canvas — strokes sync via RTCDataChannel.',
    tags: ['canvas', 'RTCDataChannel', 'collaboration', 'drawing'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section7-cuttingedge/CollaborativeWhiteboard')),
  },
  {
    id: 'webAudio-synth',
    title: 'WebAudio Synth Jam',
    path: '/demos/webAudio-synth',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Play synthesizer notes together — audio generated via Tone.js, streamed over WebRTC.',
    tags: ['Tone.js', 'Web Audio', 'synthesizer', 'RTCDataChannel', 'jam'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section7-cuttingedge/WebAudioSynth')),
  },
  {
    id: 'color-palette',
    title: 'Live Color Palette',
    path: '/demos/color-palette',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'Extract the dominant color palette from your live webcam feed using real-time color quantization.',
    tags: ['getUserMedia', 'canvas', 'color quantization', 'ImageData', 'palette'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/ColorPalette')),
  },
  {
    id: 'beat-machine',
    title: 'Collaborative Beat Machine',
    path: '/demos/beat-machine',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Build beats together — a 16-step drum sequencer powered by Tone.js, synced over RTCDataChannel.',
    tags: ['Tone.js', 'Web Audio', 'sequencer', 'RTCDataChannel', 'drum machine'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section7-cuttingedge/BeatMachine')),
  },
  {
    id: 'fractal-explorer',
    title: 'Fractal Explorer',
    path: '/demos/fractal-explorer',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'Explore the Mandelbrot set with smooth coloring — pan, zoom, and sync your viewport over DataChannel.',
    tags: ['canvas', 'ImageData', 'Mandelbrot', 'fractal', 'DataChannel', 'sync'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/FractalExplorer')),
  },
  {
    id: 'gravity-sim',
    title: 'Particle Gravity Sim',
    path: '/demos/gravity-sim',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'Click to place gravity wells and watch particles orbit — well positions sync over RTCDataChannel.',
    tags: ['canvas', 'N-body simulation', 'physics', 'DataChannel', 'particles'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/GravitySim')),
  },
  {
    id: 'webrtc-theremin',
    title: 'WebRTC Theremin',
    path: '/demos/webrtc-theremin',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'Play a virtual theremin with your mouse — pitch and volume control via Tone.js, streamed over WebRTC.',
    tags: ['Tone.js', 'Oscillator', 'MediaStreamDestination', 'theremin', 'Web Audio'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/WebRTCTheremin')),
  },
  {
    id: 'slit-scan',
    title: 'Slit-Scan Camera',
    path: '/demos/slit-scan',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'Each video frame contributes one column of pixels — accumulate them for psychedelic temporal distortion.',
    tags: ['getUserMedia', 'canvas', 'ImageData', 'slit-scan', 'time-stretch'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/SlitScanCamera')),
  },
  {
    id: 'shader-stream',
    title: 'Animated Shader Stream',
    path: '/demos/shader-stream',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'GLSL fragment shaders rendered in WebGL, captured via captureStream(), and streamed over WebRTC loopback.',
    tags: ['WebGL', 'GLSL', 'shader', 'captureStream', 'loopback'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/ShaderStream')),
  },
  {
    id: 'fourier-draw',
    title: 'Fourier Drawing Machine',
    path: '/demos/fourier-draw',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Draw any shape and watch it reconstructed by spinning Fourier epicycles — share your drawing via DataChannel.',
    tags: ['DFT', 'Fourier', 'epicycles', 'canvas', 'DataChannel'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/FourierDraw')),
  },
  {
    id: 'karaoke-machine',
    title: 'Karaoke Machine',
    path: '/demos/karaoke-machine',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'A Tone.js backing track with scrolling lyrics — beat positions sync over DataChannel so all peers are in time.',
    tags: ['Tone.js', 'Transport', 'karaoke', 'lyrics', 'audio stream'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section7-cuttingedge/KaraokeMachine')),
  },
  {
    id: 'pixel-sort-glitch',
    title: 'Pixel Sort Glitch Cam',
    path: '/demos/pixel-sort-glitch',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'Apply iconic pixel-sorting glitch art to your live webcam — sort rows by luminance, hue, or saturation and stream it.',
    tags: ['getUserMedia', 'canvas', 'ImageData', 'pixel sorting', 'glitch art', 'captureStream'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/PixelSortGlitch')),
  },
  {
    id: 'spatial-audio-room',
    title: 'Spatial Audio Room',
    path: '/demos/spatial-audio-room',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'A virtual 2D room where avatar proximity controls volume — Web Audio PannerNode (HRTF) for 3D positional audio.',
    tags: ['PannerNode', 'HRTF', 'Web Audio', 'spatial audio', 'DataChannel', 'getUserMedia'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section7-cuttingedge/SpatialAudioRoom')),
  },
  {
    id: 'physics-whiteboard',
    title: 'Physics Whiteboard',
    path: '/demos/physics-whiteboard',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'Draw shapes and watch them fall, bounce, and tumble under gravity — synchronized over RTCDataChannel.',
    tags: ['canvas', 'physics', 'gravity', 'DataChannel', 'drawing', 'simulation'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/PhysicsWhiteboard')),
  },
  {
    id: 'matrix-rain',
    title: 'Matrix Digital Rain',
    path: '/demos/matrix-rain',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'The iconic Matrix rain on canvas — captured via captureStream() and streamed over WebRTC.',
    tags: ['canvas', 'captureStream', 'MediaStream', 'animation', 'loopback'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/MatrixRain')),
  },
  {
    id: 'kaleidoscope-webcam',
    title: 'Kaleidoscope Webcam',
    path: '/demos/kaleidoscope-webcam',
    section: 'cuttingedge',
    difficulty: 'intermediate',
    description: 'Transform your live webcam into a mesmerizing kaleidoscope using Canvas 2D clip and rotate.',
    tags: ['getUserMedia', 'canvas', 'captureStream', 'transform', 'clip'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/KaleidoscopeWebcam')),
  },
  {
    id: 'quantum-entanglement',
    title: 'Quantum Entanglement',
    path: '/demos/quantum-entanglement',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Bloch sphere qubits in superposition collapse via Born rule — entangled pair anti-correlates instantly over RTCDataChannel.',
    tags: ['Three.js', 'WebGL', 'RTCDataChannel', 'Bloch sphere', 'quantum'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/QuantumEntanglement')),
  },
  {
    id: 'collab-shader-lab',
    title: 'Collaborative Shader Lab',
    path: '/demos/collab-shader-lab',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Live GLSL fragment shader editor with webcam texture — both peers edit and see the same shader in real time via DataChannel.',
    tags: ['WebGL', 'GLSL', 'shader', 'RTCDataChannel', 'webcam', 'collaboration'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/CollabShaderLab')),
  },
  {
    id: 'webgl-plasma-stream',
    title: 'WebGL Plasma Stream',
    path: '/demos/webgl-plasma-stream',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Demo-scene plasma over webcam with parameter sync via RTCDataChannel — canvas captured via captureStream() and looped through WebRTC.',
    tags: ['WebGL', 'GLSL', 'plasma', 'captureStream', 'RTCDataChannel', 'webcam'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/WebGLPlasmaStream')),
  },
  {
    id: 'gradient-nebula',
    title: 'Gradient Nebula',
    path: '/demos/gradient-nebula',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Craft perceptual peer-synced nebula gradients with Culori and RTCDataChannel.',
    tags: ['RTCDataChannel', 'Culori', 'OKLCH', 'gradient', 'design'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/GradientNebula')),
  },
  {
    id: 'signal-storm',
    title: 'Signal Storm',
    path: '/demos/signal-storm',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Synchronize a procedural network weather field generated with simplex-noise.',
    tags: ['RTCDataChannel', 'simplex-noise', 'simulation', 'canvas', 'generative'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/SignalStorm')),
  },

  // Section 8 — Fun & Games
  {
    id: 'multiplayer-pong',
    title: 'Multiplayer Pong',
    path: '/demos/multiplayer-pong',
    section: 'games',
    difficulty: 'intermediate',
    description: 'Classic Pong with paddle positions synced via RTCDataChannel — two players, one page.',
    tags: ['RTCDataChannel', 'canvas', 'game', 'keyboard', 'loopback'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/MultiplayerPong')),
  },
  {
    id: 'etch-a-sketch',
    title: 'Cooperative Etch-a-Sketch',
    path: '/demos/etch-a-sketch',
    section: 'games',
    difficulty: 'beginner',
    description: 'Draw on a shared canvas where one peer controls X and the other controls Y via RTCDataChannel.',
    tags: ['RTCDataChannel', 'canvas', 'cooperative', 'drawing', 'keyboard'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/EtchASketch')),
  },
  {
    id: 'confetti-party',
    title: 'Confetti Party',
    path: '/demos/confetti-party',
    section: 'games',
    difficulty: 'beginner',
    description: 'Trigger canvas-confetti explosions that sync to all peers in the room via RTCDataChannel.',
    tags: ['RTCDataChannel', 'canvas-confetti', 'animation', 'fun', 'multi-tab'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section8-games/ConfettiParty')),
  },
  {
    id: 'pixel-art-collab',
    title: 'Collaborative Pixel Art',
    path: '/demos/pixel-art-collab',
    section: 'games',
    difficulty: 'beginner',
    description: 'Paint on a shared 32×32 canvas — every stroke syncs to your peer via RTCDataChannel.',
    tags: ['RTCDataChannel', 'canvas', 'pixel art', 'collaboration', 'drawing'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/PixelArtCollab')),
  },
  {
    id: 'snake-race',
    title: 'Snake Race',
    path: '/demos/snake-race',
    section: 'games',
    difficulty: 'intermediate',
    description: 'Two snakes compete for the same food — new food positions sync over RTCDataChannel.',
    tags: ['RTCDataChannel', 'canvas', 'game', 'snake', 'competitive'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/SnakeRace')),
  },
  {
    id: 'dice-roll-room',
    title: 'Dice Roll Room',
    path: '/demos/dice-roll-room',
    section: 'games',
    difficulty: 'beginner',
    description: 'Roll dice together — every roll is broadcast to all peers in the room via RTCDataChannel.',
    tags: ['RTCDataChannel', 'SVG', 'dice', 'tabletop', 'signaling'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section8-games/DiceRollRoom')),
  },
  {
    id: 'shared-cursors',
    title: 'Shared Cursors',
    path: '/demos/shared-cursors',
    section: 'games',
    difficulty: 'beginner',
    description: 'See everyone\'s mouse cursor in real time — throttled position broadcast over RTCDataChannel.',
    tags: ['RTCDataChannel', 'mousemove', 'cursor', 'collaboration', 'awareness'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section8-games/SharedCursors')),
  },
  {
    id: 'reaction-duel',
    title: 'Reaction Time Duel',
    path: '/demos/reaction-duel',
    section: 'games',
    difficulty: 'beginner',
    description: 'Race a peer to click when the color flashes — reaction times compared in real time over RTCDataChannel.',
    tags: ['RTCDataChannel', 'reaction time', 'game', 'competitive', 'timing'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/ReactionDuel')),
  },
  {
    id: 'voice-puppet',
    title: 'Voice-Controlled Puppet',
    path: '/demos/voice-puppet',
    section: 'games',
    difficulty: 'beginner',
    description: 'Speak commands and a canvas character comes to life — wave, jump, spin, dance, and more synced via DataChannel.',
    tags: ['SpeechRecognition', 'Web Speech API', 'canvas', 'animation', 'DataChannel'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/VoicePuppet')),
  },
  {
    id: 'drum-pad',
    title: 'Drum Pad',
    path: '/demos/drum-pad',
    section: 'games',
    difficulty: 'beginner',
    description: 'A 9-pad drum kit with Tone.js — audio streams over WebRTC while pad hits sync to peers via DataChannel.',
    tags: ['Tone.js', 'MembraneSynth', 'NoiseSynth', 'drum', 'audio stream'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/DrumPad')),
  },
  {
    id: 'wordle-duel',
    title: 'Wordle Duel',
    path: '/demos/wordle-duel',
    section: 'games',
    difficulty: 'beginner',
    description: 'Race to solve the daily Wordle — same word derived from the date, solve-status synced over DataChannel.',
    tags: ['RTCDataChannel', 'word game', 'Wordle', 'daily', 'competitive'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/WordleDuel')),
  },
  {
    id: 'qr-teleporter',
    title: 'QR Code Teleporter',
    path: '/demos/qr-teleporter',
    section: 'games',
    difficulty: 'intermediate',
    description: 'Encode a message as a QR code, stream it over WebRTC video, and decode it on the other end with jsQR.',
    tags: ['canvas', 'captureStream', 'qrcode', 'jsQR', 'video stream'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/QrTeleporter')),
  },
  {
    id: 'chess-relay',
    title: 'Chess Relay',
    path: '/demos/chess-relay',
    section: 'games',
    difficulty: 'intermediate',
    description: 'Relay legal chess moves peer-to-peer and rebuild the board with chess.js.',
    tags: ['RTCDataChannel', 'chess.js', 'board game', 'state sync', 'moves'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section8-games/ChessRelay')),
  },
  // Section 9 — Mashups
  {
    id: 'motion-confetti',
    title: 'Motion-Triggered Confetti',
    path: '/demos/motion-confetti',
    section: 'mashups',
    difficulty: 'beginner',
    description: 'MASHUP: Motion Detector + Confetti Party — wave at the camera and confetti fires across all connected peers.',
    tags: ['getUserMedia', 'canvas', 'motion', 'canvas-confetti', 'mashup'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section9-mashups/MotionConfetti')),
  },
  {
    id: 'ascii-screen-share',
    title: 'ASCII Screen Share',
    path: '/demos/ascii-screen-share',
    section: 'mashups',
    difficulty: 'intermediate',
    description: 'MASHUP: Screen Share + ASCII Webcam — share your screen as live ASCII art streamed over WebRTC.',
    tags: ['getDisplayMedia', 'canvas', 'ASCII', 'captureStream', 'mashup'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section9-mashups/AsciiScreenShare')),
  },
  {
    id: 'video-call-chat',
    title: 'Video Call + Chat',
    path: '/demos/video-call-chat',
    section: 'mashups',
    difficulty: 'intermediate',
    description: 'MASHUP: Video Call + P2P Chat — one RTCPeerConnection carries A/V tracks and a DataChannel text chat.',
    tags: ['RTCPeerConnection', 'getUserMedia', 'RTCDataChannel', 'video call', 'chat'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section9-mashups/VideoCallChat')),
  },
  {
    id: 'gravity-theremin',
    title: 'Gravity Theremin',
    path: '/demos/gravity-theremin',
    section: 'mashups',
    difficulty: 'intermediate',
    description: 'MASHUP: Particle Gravity Sim + Theremin — particle physics drives Tone.js pitch and volume in real time.',
    tags: ['Tone.js', 'N-body', 'canvas', 'physics', 'audio', 'mashup'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section9-mashups/GravityTheremin')),
  },
  {
    id: 'remote-desktop-control',
    title: 'Remote Desktop Control',
    path: '/demos/remote-desktop-control',
    section: 'mashups',
    difficulty: 'advanced',
    description: 'One peer streams a live canvas mini-app; the other controls it via mouse events sent over RTCDataChannel.',
    tags: ['captureStream', 'RTCDataChannel', 'remote control', 'event injection', 'mashup'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section9-mashups/RemoteDesktopControl')),
  },
  {
    id: 'encrypted-clipboard',
    title: 'Encrypted Clipboard',
    path: '/demos/encrypted-clipboard',
    section: 'mashups',
    difficulty: 'intermediate',
    description: 'MASHUP: P2P Clipboard + Encrypted Messenger — clipboard content is AES-256-GCM encrypted before every send.',
    tags: ['Web Crypto API', 'PBKDF2', 'AES-GCM', 'clipboard', 'encryption', 'mashup'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section9-mashups/EncryptedClipboard')),
  },
  // Section 7 — new demos (batch 2)
  {
    id: 'binaural-beat-studio',
    title: 'Binaural Beat Studio',
    path: '/demos/binaural-beat-studio',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Precision binaural beats for brainwave entrainment — Delta sleep to Gamma peak focus. Stream synchronized beats over WebRTC. Headphones required.',
    tags: ['Web Audio API', 'OscillatorNode', 'ChannelMerger', 'binaural', 'brainwave', 'MediaStreamDestination'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/BinauralBeatStudio')),
  },
  {
    id: 'network-synesthesia',
    title: 'Network Synesthesia',
    path: '/demos/network-synesthesia',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'RTT controls pitch, jitter drives vibrato, packet loss triggers glitch sounds — your WebRTC network stats become ambient music via Tone.js.',
    tags: ['RTCStatsReport', 'getStats', 'Tone.js', 'PolySynth', 'synesthesia', 'sonification'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/NetworkSynesthesia')),
  },
  {
    id: 'soundscape-garden',
    title: 'Soundscape Garden',
    path: '/demos/soundscape-garden',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Click to plant sound seeds — Rose (PluckSynth), Crystal (MetalSynth), Drum (MembraneSynth), Wind (AMSynth). Position maps to pitch and rhythm. Sync gardens via DataChannel.',
    tags: ['Tone.js', 'PluckSynth', 'MetalSynth', 'RTCDataChannel', 'generative', 'ambient'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/SoundscapeGarden')),
  },
  {
    id: 'midi-jam',
    title: 'MIDI Jam Session',
    path: '/demos/midi-jam',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Connect a real MIDI keyboard via the Web MIDI API or play the on-screen piano. MIDI events travel over RTCDataChannel and are synthesized with Tone.js PolySynth.',
    tags: ['Web MIDI API', 'Tone.js', 'PolySynth', 'RTCDataChannel', 'MIDI', 'piano', 'music'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/MIDIJam')),
  },
  {
    id: 'body-puppet-show',
    title: 'Body Puppet Show',
    path: '/demos/body-puppet-show',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'TF.js MoveNet transmits only 17 keypoints (~340 bytes/frame) over DataChannel — zero video. The other side renders a live animated puppet from coordinates alone.',
    tags: ['TensorFlow.js', 'MoveNet', 'pose detection', 'RTCDataChannel', 'low-bandwidth', 'puppet'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/BodyPuppetShow')),
  },
  {
    id: 'live-code-collab',
    title: 'Live Code Collab',
    path: '/demos/live-code-collab',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Real-time collaborative JavaScript editor over RTCDataChannel. Both peers type simultaneously. Run code in a sandboxed iframe with live console output.',
    tags: ['RTCDataChannel', 'collaborative editing', 'sandbox', 'iframe', 'code execution', 'pair programming'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/LiveCodeCollab')),
  },
  // Section 7 additions
  {
    id: 'face-filter-party',
    title: 'Face Filter Party',
    path: '/demos/face-filter-party',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'AR face filters powered by TF.js MediaPipe FaceMesh — glasses, halo, fire crown, cat ears, streamed via WebRTC loopback.',
    tags: ['TensorFlow.js', 'FaceMesh', 'face landmarks', 'AR', 'canvas', 'captureStream'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/FaceFilterParty')),
  },

  // Section 9 mashups continued
  {
    id: 'motion-beatbox',
    title: 'Motion Beatbox',
    path: '/demos/motion-beatbox',
    section: 'mashups',
    difficulty: 'advanced',
    description: 'MASHUP: MotionDetector + BeatMachine — raise your hands to trigger drums, crouch for bass. Your body IS the beat machine.',
    tags: ['TensorFlow.js', 'MoveNet', 'pose detection', 'Tone.js', 'drums', 'canvas', 'mashup'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section9-mashups/MotionBeatbox')),
  },
  {
    id: 'glitch-video-call',
    title: 'Glitch Video Call',
    path: '/demos/glitch-video-call',
    section: 'mashups',
    difficulty: 'advanced',
    description: 'MASHUP: VideoCall + PixelSortGlitch — peer-to-peer video call where both streams are pixel-sort glitched. Intensity syncs via DataChannel.',
    tags: ['getUserMedia', 'RTCPeerConnection', 'pixel sort', 'glitch art', 'DataChannel', 'mashup'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section9-mashups/GlitchVideoCall')),
  },
  {
    id: 'fractal-ambient',
    title: 'Fractal Ambient',
    path: '/demos/fractal-ambient',
    section: 'mashups',
    difficulty: 'advanced',
    description: 'MASHUP: FractalExplorer + WebAudioSynth — navigate the Mandelbrot set and let the fractal compose ambient music. Synced with peer via DataChannel.',
    tags: ['Mandelbrot', 'canvas', 'Tone.js', 'Web Audio', 'DataChannel', 'fractal', 'mashup'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section9-mashups/FractalAmbient')),
  },
  {
    id: 'physics-poetry',
    title: 'Physics Poetry',
    path: '/demos/physics-poetry',
    section: 'mashups',
    difficulty: 'intermediate',
    description: 'MASHUP: P2PChat + PhysicsWhiteboard — type messages and watch each word become a Matter.js physics body that tumbles and bounces.',
    tags: ['Matter.js', 'RTCDataChannel', 'physics', 'chat', 'canvas', 'mashup'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section9-mashups/PhysicsPoetry')),
  },
  {
    id: 'echo-chamber',
    title: 'Echo Chamber',
    path: '/demos/echo-chamber',
    section: 'mashups',
    difficulty: 'advanced',
    description: 'MASHUP: VoiceChanger + SpatialAudioRoom — move your avatar with WASD, pick a voice effect, and hear 3D spatial audio shift as you move.',
    tags: ['PannerNode', 'HRTF', 'Web Audio', 'voice effects', 'spatial audio', 'canvas', 'mashup'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section9-mashups/EchoChamber')),
  },
];

export function getDemosBySection(sectionId: SectionId): DemoMeta[] {
  return DEMOS.filter((d) => d.section === sectionId);
}

export function getDemoById(id: string): DemoMeta | undefined {
  return DEMOS.find((d) => d.id === id);
}
