import { lazy } from 'react';
import type { DemoMeta, SectionMeta, SectionId } from '@/types/demo';

export const SECTIONS: SectionMeta[] = [
  { id: 'fundamentals', title: 'Fundamentals', icon: '🧱' },
  { id: 'media', title: 'Media & Streams', icon: '📷' },
  { id: 'datachannels', title: 'Data Channels', icon: '📡' },
  { id: 'audiovideo', title: 'Audio & Video', icon: '🎥' },
  { id: 'advanced', title: 'Advanced', icon: '🔬' },
  { id: 'multiparty', title: 'Multi-Party', icon: '👥' },
  { id: 'cuttingedge', title: 'Cutting Edge', icon: '🚀' },
];

export const DEMOS: DemoMeta[] = [
  // Section 1 — Fundamentals
  {
    id: 'hello-webrtc',
    title: 'Hello WebRTC',
    path: '/demos/hello-webrtc',
    section: 'fundamentals',
    difficulty: 'beginner',
    description: 'Your first RTCPeerConnection — connect two peers on the same page via loopback.',
    tags: ['RTCPeerConnection', 'loopback', 'offer', 'answer'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section1-fundamentals/HelloWebRTC')),
  },
  {
    id: 'connection-states',
    title: 'Connection States',
    path: '/demos/connection-states',
    section: 'fundamentals',
    difficulty: 'beginner',
    description: 'Watch the RTCPeerConnection state machine animate through every state transition.',
    tags: ['connectionState', 'iceConnectionState', 'state machine'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section1-fundamentals/ConnectionStates')),
  },
  {
    id: 'sdp-inspector',
    title: 'SDP Inspector',
    path: '/demos/sdp-inspector',
    section: 'fundamentals',
    difficulty: 'beginner',
    description: 'Paste any SDP and explore its structure — codecs, ICE candidates, extensions.',
    tags: ['SDP', 'offer', 'answer', 'codec', 'ice'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section1-fundamentals/SdpInspector')),
  },
  {
    id: 'ice-candidate-explorer',
    title: 'ICE Candidate Explorer',
    path: '/demos/ice-candidate-explorer',
    section: 'fundamentals',
    difficulty: 'beginner',
    description: 'See every ICE candidate as it arrives — host, server reflexive, and relay types.',
    tags: ['ICE', 'candidate', 'STUN', 'TURN', 'trickle'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section1-fundamentals/IceCandidateExplorer')),
  },
  {
    id: 'manual-signaling',
    title: 'Manual Signaling',
    path: '/demos/manual-signaling',
    section: 'fundamentals',
    difficulty: 'beginner',
    description: 'Copy-paste offer and answer SDP between two browser tabs — no server needed.',
    tags: ['signaling', 'offer', 'answer', 'copy-paste'],
    needsServer: false,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section1-fundamentals/ManualSignaling')),
  },

  // Section 2 — Media & Streams
  {
    id: 'camera-mic-preview',
    title: 'Camera & Mic Preview',
    path: '/demos/camera-mic-preview',
    section: 'media',
    difficulty: 'beginner',
    description: 'Request camera and microphone access and preview the stream locally.',
    tags: ['getUserMedia', 'MediaStream', 'camera', 'microphone'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section2-media/CameraMicPreview')),
  },
  {
    id: 'device-picker',
    title: 'Device Picker',
    path: '/demos/device-picker',
    section: 'media',
    difficulty: 'beginner',
    description: 'Enumerate all cameras and microphones and switch between them.',
    tags: ['enumerateDevices', 'MediaDeviceInfo', 'camera', 'microphone'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section2-media/DevicePicker')),
  },
  {
    id: 'screen-share',
    title: 'Screen Share',
    path: '/demos/screen-share',
    section: 'media',
    difficulty: 'beginner',
    description: 'Share your screen or a window and view it through a loopback WebRTC connection.',
    tags: ['getDisplayMedia', 'screen share', 'loopback'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section2-media/ScreenShare')),
  },
  {
    id: 'media-constraints-lab',
    title: 'Media Constraints Lab',
    path: '/demos/media-constraints-lab',
    section: 'media',
    difficulty: 'intermediate',
    description: 'Experiment with resolution, frame rate, and codec constraints in real time.',
    tags: ['MediaTrackConstraints', 'applyConstraints', 'resolution', 'framerate'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section2-media/MediaConstraintsLab')),
  },

  // Section 3 — Data Channels
  {
    id: 'p2p-chat',
    title: 'P2P Chat',
    path: '/demos/p2p-chat',
    section: 'datachannels',
    difficulty: 'intermediate',
    description: 'Send text messages directly between two browser tabs via an RTCDataChannel.',
    tags: ['RTCDataChannel', 'chat', 'p2p', 'text'],
    needsServer: false,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section3-datachannels/P2PChat')),
  },
  {
    id: 'data-channel-types',
    title: 'Data Channel Types',
    path: '/demos/data-channel-types',
    section: 'datachannels',
    difficulty: 'intermediate',
    description: 'Compare ordered vs unordered, reliable vs unreliable data channel modes.',
    tags: ['RTCDataChannel', 'ordered', 'reliable', 'maxRetransmits'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/DataChannelTypes')),
  },
  {
    id: 'file-transfer',
    title: 'File Transfer',
    path: '/demos/file-transfer',
    section: 'datachannels',
    difficulty: 'intermediate',
    description: 'Transfer files between tabs with backpressure control and SHA-256 verification.',
    tags: ['RTCDataChannel', 'file', 'ArrayBuffer', 'backpressure', 'SHA-256'],
    needsServer: false,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section3-datachannels/FileTransfer')),
  },
  {
    id: 'json-state-sync',
    title: 'JSON State Sync',
    path: '/demos/json-state-sync',
    section: 'datachannels',
    difficulty: 'intermediate',
    description: 'Keep a JSON object synchronized between two peers in real time.',
    tags: ['RTCDataChannel', 'JSON', 'sync', 'state'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section3-datachannels/JsonStateSync')),
  },

  // Section 4 — Audio & Video
  {
    id: 'video-call',
    title: 'Video Call',
    path: '/demos/video-call',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Full A/V video call between two tabs with automatic WebSocket signaling.',
    tags: ['video', 'audio', 'WebSocket', 'signaling', 'getUserMedia'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section4-audiovideo/VideoCall')),
  },
  {
    id: 'audio-visualizer',
    title: 'Audio Visualizer',
    path: '/demos/audio-visualizer',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Visualize audio waveforms and frequency spectra through a WebRTC loopback.',
    tags: ['Web Audio API', 'AnalyserNode', 'waveform', 'spectrum'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/AudioVisualizer')),
  },
  {
    id: 'video-effects',
    title: 'Video Effects',
    path: '/demos/video-effects',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Apply grayscale, blur, and edge detection to video via Canvas pipeline.',
    tags: ['canvas', 'captureStream', 'video effects', 'CanvasRenderingContext2D'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/VideoEffects')),
  },
  {
    id: 'bandwidth-quality',
    title: 'Bandwidth & Quality',
    path: '/demos/bandwidth-quality',
    section: 'audiovideo',
    difficulty: 'intermediate',
    description: 'Control bitrate constraints and see quality impact in a loopback call.',
    tags: ['RTCRtpSender', 'setParameters', 'bitrate', 'bandwidth'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section4-audiovideo/BandwidthQuality')),
  },

  // Section 5 — Advanced
  {
    id: 'stats-dashboard',
    title: 'Stats Dashboard',
    path: '/demos/stats-dashboard',
    section: 'advanced',
    difficulty: 'intermediate',
    description: 'Live RTCStatsReport charts — bitrate, packet loss, jitter, RTT over time.',
    tags: ['RTCStatsReport', 'getStats', 'bitrate', 'packet loss', 'charts'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section5-advanced/StatsDashboard')),
  },
  {
    id: 'stun-turn-tester',
    title: 'STUN/TURN Tester',
    path: '/demos/stun-turn-tester',
    section: 'advanced',
    difficulty: 'intermediate',
    description: 'Test custom STUN/TURN servers and verify candidate types gathered.',
    tags: ['STUN', 'TURN', 'ICE', 'RTCIceServer', 'candidate'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section5-advanced/StunTurnTester')),
  },
  {
    id: 'screen-annotation',
    title: 'Screen Share + Annotation',
    path: '/demos/screen-annotation',
    section: 'advanced',
    difficulty: 'advanced',
    description: 'Share your screen and annotate it collaboratively via WebSocket signaling.',
    tags: ['getDisplayMedia', 'canvas', 'annotation', 'collaboration'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section5-advanced/ScreenAnnotation')),
  },

  // Section 6 — Multi-Party
  {
    id: 'mesh-network',
    title: 'Mesh Network',
    path: '/demos/mesh-network',
    section: 'multiparty',
    difficulty: 'advanced',
    description: 'Connect 3-4 peers in a full mesh — every peer connects to every other peer.',
    tags: ['mesh', 'multi-party', 'RTCPeerConnection', 'signaling'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section6-multiparty/MeshNetwork')),
  },
  {
    id: 'broadcaster-viewer',
    title: 'Broadcaster / Viewer',
    path: '/demos/broadcaster-viewer',
    section: 'multiparty',
    difficulty: 'advanced',
    description: 'One broadcaster sends to multiple viewers — SFU-style topology without an SFU.',
    tags: ['broadcast', 'viewer', 'one-to-many', 'signaling'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section6-multiparty/BroadcasterViewer')),
  },
  {
    id: 'group-chat',
    title: 'Group Chat',
    path: '/demos/group-chat',
    section: 'multiparty',
    difficulty: 'advanced',
    description: 'Multi-peer text chat over RTCDataChannels — no server relay for messages.',
    tags: ['RTCDataChannel', 'group', 'mesh', 'chat'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section6-multiparty/GroupChat')),
  },

  // Section 7 — Cutting Edge
  {
    id: '3d-video',
    title: '3D Video with Three.js',
    path: '/demos/3d-video',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Stream video onto a 3D spinning cube texture via Three.js and WebRTC loopback.',
    tags: ['Three.js', 'WebGL', 'VideoTexture', '3D', 'loopback'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/ThreeDVideo')),
  },
  {
    id: 'virtual-background',
    title: 'Virtual Background (ML)',
    path: '/demos/virtual-background',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Replace or blur your background using TensorFlow.js body segmentation.',
    tags: ['TensorFlow.js', 'body segmentation', 'virtual background', 'ML', 'canvas'],
    needsServer: false,
    needsMultipleTabs: false,
    component: lazy(() => import('@/demos/section7-cuttingedge/VirtualBackground')),
  },
  {
    id: 'collaborative-whiteboard',
    title: 'Collaborative Whiteboard',
    path: '/demos/collaborative-whiteboard',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Draw together on a shared canvas — strokes sync via RTCDataChannel.',
    tags: ['canvas', 'RTCDataChannel', 'collaboration', 'drawing'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section7-cuttingedge/CollaborativeWhiteboard')),
  },
  {
    id: 'webAudio-synth',
    title: 'WebAudio Synth Jam',
    path: '/demos/webAudio-synth',
    section: 'cuttingedge',
    difficulty: 'advanced',
    description: 'Play synthesizer notes together — audio generated via Tone.js, streamed over WebRTC.',
    tags: ['Tone.js', 'Web Audio', 'synthesizer', 'RTCDataChannel', 'jam'],
    needsServer: true,
    needsMultipleTabs: true,
    component: lazy(() => import('@/demos/section7-cuttingedge/WebAudioSynth')),
  },
];

export function getDemosBySection(sectionId: SectionId): DemoMeta[] {
  return DEMOS.filter((d) => d.section === sectionId);
}

export function getDemoById(id: string): DemoMeta | undefined {
  return DEMOS.find((d) => d.id === id);
}
