import { useEffect, useMemo, useRef, useState } from 'react';
import seedrandom from 'seedrandom';
import { DemoLayout } from '@/components/layout/DemoLayout';
import { Logger } from '@/lib/logger';
import { createLoopbackDataPair, type LoopbackDataPair } from '@/lib/createLoopbackDataPair';

interface UniverseState {
  seed: string;
  count: number;
}

interface Star {
  x: number;
  y: number;
  r: number;
  hue: number;
}

const CODE = `const rng = seedrandom(seed);
const stars = Array.from({ length: count }, () => ({
  x: rng() * 100,
  y: rng() * 100,
  r: 0.6 + rng() * 2.2,
}));`;

function createStars(seed: string, count: number): Star[] {
  const rng = seedrandom(seed || 'zero');
  return Array.from({ length: count }, () => ({
    x: rng() * 100,
    y: rng() * 100,
    r: 0.6 + rng() * 2.2,
    hue: 190 + rng() * 120,
  }));
}

export default function SeededUniverse() {
  const logger = useMemo(() => new Logger(), []);
  const [connected, setConnected] = useState(false);
  const [stateA, setStateA] = useState<UniverseState>({ seed: 'nebula-01', count: 120 });
  const [stateB, setStateB] = useState<UniverseState>({ seed: 'nebula-01', count: 120 });
  const pairRef = useRef<LoopbackDataPair | null>(null);

  const starsA = useMemo(() => createStars(stateA.seed, stateA.count), [stateA]);
  const starsB = useMemo(() => createStars(stateB.seed, stateB.count), [stateB]);

  const disconnect = () => {
    pairRef.current?.close();
    pairRef.current = null;
    setConnected(false);
  };

  const connect = async () => {
    disconnect();
    const pair = await createLoopbackDataPair('seeded-universe');
    pairRef.current = pair;
    pair.dcA.onmessage = (ev) => {
      const msg = JSON.parse(ev.data as string) as { type: 'universe'; payload: UniverseState };
      if (msg.type === 'universe') setStateA(msg.payload);
    };
    pair.dcB.onmessage = (ev) => {
      const msg = JSON.parse(ev.data as string) as { type: 'universe'; payload: UniverseState };
      if (msg.type === 'universe') setStateB(msg.payload);
    };
    setConnected(true);
    logger.success('Seeded universe link established.');
  };

  const update = (side: 'A' | 'B', patch: Partial<UniverseState>) => {
    if (side === 'A') {
      const next = { ...stateA, ...patch };
      setStateA(next);
      if (pairRef.current?.dcA.readyState === 'open') pairRef.current.dcA.send(JSON.stringify({ type: 'universe', payload: next }));
    } else {
      const next = { ...stateB, ...patch };
      setStateB(next);
      if (pairRef.current?.dcB.readyState === 'open') pairRef.current.dcB.send(JSON.stringify({ type: 'universe', payload: next }));
    }
  };

  useEffect(() => () => disconnect(), []);

  return (
    <DemoLayout
      title="Seeded Universe Sync"
      difficulty="beginner"
      description="Deterministic starfields generated by seedrandom and synchronized over WebRTC."
      explanation={<p className="text-sm">With a shared seed, both peers produce the same universe locally, so only tiny seed updates cross the network.</p>}
      demo={
        <div className="space-y-4">
          <div className="flex gap-2">
            {!connected ? (
              <button onClick={connect} className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-sm rounded-lg">Connect</button>
            ) : (
              <button onClick={disconnect} className="px-4 py-2 bg-rose-700 hover:bg-rose-600 text-white text-sm rounded-lg">Disconnect</button>
            )}
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {[
              { side: 'A' as const, title: 'Peer A', state: stateA, stars: starsA },
              { side: 'B' as const, title: 'Peer B', state: stateB, stars: starsB },
            ].map(({ side, title, state, stars }) => (
              <div key={side} className="space-y-2">
                <p className="text-xs text-zinc-500">{title}</p>
                <div className="flex gap-2">
                  <input value={state.seed} onChange={(e) => update(side, { seed: e.target.value })} disabled={!connected} className="flex-1 bg-surface-0 border border-zinc-700 rounded px-2 py-1 text-xs text-zinc-200 disabled:opacity-50" />
                  <input type="range" min={40} max={260} value={state.count} onChange={(e) => update(side, { count: Number(e.target.value) })} disabled={!connected} />
                </div>
                <svg viewBox="0 0 100 60" className="w-full h-48 border border-zinc-800 rounded-lg bg-black">
                  {stars.map((s, i) => (
                    <circle key={i} cx={s.x} cy={(s.y * 0.6)} r={s.r} fill={`hsl(${s.hue} 90% 75%)`} opacity={0.85} />
                  ))}
                </svg>
              </div>
            ))}
          </div>
        </div>
      }
      logger={logger}
      codeSnippet={{ code: CODE, title: 'Deterministic generation from seed' }}
      hints={['Both sides should match exactly when seed and star count match.', 'This pattern minimizes payload size for procedural worlds.']}
    />
  );
}
